/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of the event. who has triggered the event.
 * @export
 * @enum {string}
 */

export const EventType = {
    EXECUTIVE: 'executive',
    ORACLE: 'oracle',
    USER: 'user'
} as const;

export type EventType = typeof EventType[keyof typeof EventType];



