/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The domain of the event.
*/
export enum EventDomain {
    StableCoinSystem = <any> 'stableCoinSystem',
    Lendingpool = <any> 'lendingpool',
    Chainlink = <any> 'chainlink',
    UniswapV3 = <any> 'uniswapV3'
}
