/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Token } from './token';

export class FormattedReserveData {
    /**
    * Identifier for the reserve data.
    */
    'id': string;
    'underlyingAsset': Token;
    /**
    * Address of the associated zToken contract in hexadecimal format.
    */
    'zTokenAddress': string;
    /**
    * Address of the associated variable debt token contract in hexadecimal format.
    */
    'variableDebtTokenAddress': string;
    'borrowingEnabled': boolean;
    'isActive': boolean;
    'isFrozen': boolean;
    'usageAsCollateralEnabled': boolean;
    'reserveFactor': string;
    'baseLTVasCollateral': string;
    'reserveLiquidationThreshold': string;
    'reserveLiquidationBonus': string;
    'utilizationRate': string;
    'totalDebt': { [key: string]: string; };
    'totalLiquidity': { [key: string]: string; };
    'availableLiquidity': { [key: string]: string; };
    'supplyAPY': string;
    'supplyAPR': string;
    'variableBorrowAPY': string;
    'variableBorrowAPR': string;
    'price': { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "underlyingAsset",
            "baseName": "underlyingAsset",
            "type": "Token"
        },
        {
            "name": "zTokenAddress",
            "baseName": "zTokenAddress",
            "type": "string"
        },
        {
            "name": "variableDebtTokenAddress",
            "baseName": "variableDebtTokenAddress",
            "type": "string"
        },
        {
            "name": "borrowingEnabled",
            "baseName": "borrowingEnabled",
            "type": "boolean"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "isFrozen",
            "baseName": "isFrozen",
            "type": "boolean"
        },
        {
            "name": "usageAsCollateralEnabled",
            "baseName": "usageAsCollateralEnabled",
            "type": "boolean"
        },
        {
            "name": "reserveFactor",
            "baseName": "reserveFactor",
            "type": "string"
        },
        {
            "name": "baseLTVasCollateral",
            "baseName": "baseLTVasCollateral",
            "type": "string"
        },
        {
            "name": "reserveLiquidationThreshold",
            "baseName": "reserveLiquidationThreshold",
            "type": "string"
        },
        {
            "name": "reserveLiquidationBonus",
            "baseName": "reserveLiquidationBonus",
            "type": "string"
        },
        {
            "name": "utilizationRate",
            "baseName": "utilizationRate",
            "type": "string"
        },
        {
            "name": "totalDebt",
            "baseName": "totalDebt",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "totalLiquidity",
            "baseName": "totalLiquidity",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "availableLiquidity",
            "baseName": "availableLiquidity",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "supplyAPY",
            "baseName": "supplyAPY",
            "type": "string"
        },
        {
            "name": "supplyAPR",
            "baseName": "supplyAPR",
            "type": "string"
        },
        {
            "name": "variableBorrowAPY",
            "baseName": "variableBorrowAPY",
            "type": "string"
        },
        {
            "name": "variableBorrowAPR",
            "baseName": "variableBorrowAPR",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return FormattedReserveData.attributeTypeMap;
    }
}

