/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Token } from './token';

export class LendingpoolDeposit {
    /**
    * The Ethereum address of the user.
    */
    'user': string;
    'underlyingAsset': Token;
    'amount': { [key: string]: string; };
    /**
    * Whether the user has enabled the asset as collateral.
    */
    'usageAsCollateralEnabledOnUser': boolean;
    /**
    * The supply APY.
    */
    'supplyAPY': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "underlyingAsset",
            "baseName": "underlyingAsset",
            "type": "Token"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "usageAsCollateralEnabledOnUser",
            "baseName": "usageAsCollateralEnabledOnUser",
            "type": "boolean"
        },
        {
            "name": "supplyAPY",
            "baseName": "supplyAPY",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LendingpoolDeposit.attributeTypeMap;
    }
}

