/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LendingpoolUseAssetAsCollateralTxRequest
 */
export interface LendingpoolUseAssetAsCollateralTxRequest {
    /**
     * Ethereum address of the user
     * @type {string}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    'user': string;
    /**
     * Symbol of asset
     * @type {string}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    'symbol': string;
    /**
     * Enable or disable the asset as collateral
     * @type {boolean}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    'enabled': boolean;
}

