/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RawDutchAmount } from './raw-dutch-amount';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'quoteId'?: string;
    /**
     * 
     * @type {Array<RawDutchAmount>}
     * @memberof Order
     */
    'outputs': Array<RawDutchAmount>;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'encodedOrder': string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'signature': string;
    /**
     * 
     * @type {RawDutchAmount}
     * @memberof Order
     */
    'input': RawDutchAmount;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'orderStatus': OrderOrderStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'chainId': number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'orderHash': string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'orderType': OrderOrderTypeEnum;
}

export const OrderOrderStatusEnum = {
    OPEN: 'open',
    EXPIRED: 'expired',
    ERROR: 'error',
    CANCELLED: 'cancelled',
    FILLED: 'filled',
    INSUFFICIENT_FUNDS: 'insufficient-funds'
} as const;

export type OrderOrderStatusEnum = typeof OrderOrderStatusEnum[keyof typeof OrderOrderStatusEnum];
export const OrderOrderTypeEnum = {
    DUTCH: 'dutch',
    LIMIT: 'limit'
} as const;

export type OrderOrderTypeEnum = typeof OrderOrderTypeEnum[keyof typeof OrderOrderTypeEnum];


