/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MethodParameters } from './methodParameters';

export class PreparedTx {
    'type': string;
    'label': { [key: string]: string; };
    'gasUseEstimate': number;
    'gasFeeEstimate': { [key: string]: string; };
    'methodParameters': MethodParameters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "gasUseEstimate",
            "baseName": "gasUseEstimate",
            "type": "number"
        },
        {
            "name": "gasFeeEstimate",
            "baseName": "gasFeeEstimate",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "methodParameters",
            "baseName": "methodParameters",
            "type": "MethodParameters"
        }    ];

    static getAttributeTypeMap() {
        return PreparedTx.attributeTypeMap;
    }
}

