/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MethodParameters } from './method-parameters';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderInfo } from './order-info';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RouteItem } from './route-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';
// May contain unused imports in some cases
// @ts-ignore
import type { TradeType } from './trade-type';
// May contain unused imports in some cases
// @ts-ignore
import type { TypedData } from './typed-data';

/**
 * 
 * @export
 * @interface QuoteResponse
 */
export interface QuoteResponse {
    /**
     * 
     * @type {OrderType}
     * @memberof QuoteResponse
     */
    'type': OrderType;
    /**
     * 
     * @type {TradeType}
     * @memberof QuoteResponse
     */
    'tradeType': TradeType;
    /**
     * 
     * @type {Timestamp}
     * @memberof QuoteResponse
     */
    'time': Timestamp;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof QuoteResponse
     */
    'amount': { [key: string]: string | undefined; };
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof QuoteResponse
     */
    'quote': { [key: string]: string | undefined; };
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    'quoteId': string;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof QuoteResponse
     */
    'gasPrice': { [key: string]: string | undefined; };
    /**
     * 
     * @type {number}
     * @memberof QuoteResponse
     */
    'gasUseEstimate': number;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof QuoteResponse
     */
    'gasFeeEstimate': { [key: string]: string | undefined; };
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    'routeString': string;
    /**
     * 
     * @type {MethodParameters}
     * @memberof QuoteResponse
     */
    'methodParameters'?: MethodParameters;
    /**
     * 
     * @type {Array<RouteItem>}
     * @memberof QuoteResponse
     */
    'route': Array<RouteItem>;
    /**
     * 
     * @type {OrderInfo}
     * @memberof QuoteResponse
     */
    'orderInfo'?: OrderInfo;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    'encodedOrder'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponse
     */
    'orderHash'?: string;
    /**
     * 
     * @type {TypedData}
     * @memberof QuoteResponse
     */
    'permitData'?: TypedData;
}



