/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RawDutchAmount {
    'token': string;
    'startAmount': string;
    'endAmount': string;
    'recipient'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "startAmount",
            "baseName": "startAmount",
            "type": "string"
        },
        {
            "name": "endAmount",
            "baseName": "endAmount",
            "type": "string"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RawDutchAmount.attributeTypeMap;
    }
}

