/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Token } from './token';

export class RouteItem {
    'address': string;
    'tokenIn': Token;
    'tokenOut': Token;
    'fee': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "tokenIn",
            "baseName": "tokenIn",
            "type": "Token"
        },
        {
            "name": "tokenOut",
            "baseName": "tokenOut",
            "type": "Token"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RouteItem.attributeTypeMap;
    }
}

