/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScoreboardItem
 */
export interface ScoreboardItem {
    /**
     * 
     * @type {string}
     * @memberof ScoreboardItem
     */
    'address': string;
    /**
     * 
     * @type {number}
     * @memberof ScoreboardItem
     */
    'points': number;
}

