/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StablecoinSystemStats {
    /**
    * System surplus
    */
    'systemSurplus': { [key: string]: string; };
    /**
    * System debt
    */
    'systemDebt': { [key: string]: string; };
    /**
    * System debt ceiling
    */
    'systemDebtCeiling': { [key: string]: string; };
    /**
    * System surplus buffer
    */
    'systemSurplusBuffer': { [key: string]: string; };
    /**
    * System bad debt
    */
    'systemBadDebt': { [key: string]: string; };
    /**
    * System surplus lot size
    */
    'systemSurplusLotSize': { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "systemSurplus",
            "baseName": "systemSurplus",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "systemDebt",
            "baseName": "systemDebt",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "systemDebtCeiling",
            "baseName": "systemDebtCeiling",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "systemSurplusBuffer",
            "baseName": "systemSurplusBuffer",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "systemBadDebt",
            "baseName": "systemBadDebt",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "systemSurplusLotSize",
            "baseName": "systemSurplusLotSize",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return StablecoinSystemStats.attributeTypeMap;
    }
}

