/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChainActivity } from './chain-activity';

/**
 * 
 * @export
 * @interface StakingWithdrawTxResponse
 */
export interface StakingWithdrawTxResponse {
    /**
     * 
     * @type {ChainActivity}
     * @memberof StakingWithdrawTxResponse
     */
    'chainActivity'?: ChainActivity;
}

