/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Symbol representation
*/
export enum Symbol {
    Usd = <any> 'USD',
    Dai = <any> 'DAI',
    Usdt = <any> 'USDT',
    Usdc = <any> 'USDC',
    Wbtc = <any> 'WBTC',
    Eth = <any> 'ETH',
    Weth = <any> 'WETH',
    Zar = <any> 'ZAR',
    Tmn = <any> 'TMN'
}
