/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserStake {
    /**
    * Ethereum address of the user
    */
    'user': string;
    /**
    * The amount of asset staked in native token units
    */
    'balance': { [key: string]: string; };
    /**
    * The amount of unclaimed reward in native token units
    */
    'unclaimedReward': { [key: string]: string; };
    /**
    * Ethereum address of the staking contract
    */
    'contractAddress': string;
    /**
    * Name of staking plan
    */
    'planName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "unclaimedReward",
            "baseName": "unclaimedReward",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "contractAddress",
            "baseName": "contractAddress",
            "type": "string"
        },
        {
            "name": "planName",
            "baseName": "planName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserStake.attributeTypeMap;
    }
}

