/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTelegramRequest
 */
export interface AuthTelegramRequest {
    /**
     * Telegram init data
     * @type {string}
     * @memberof AuthTelegramRequest
     */
    initdata: string;
}

/**
 * Check if a given object implements the AuthTelegramRequest interface.
 */
export function instanceOfAuthTelegramRequest(value: object): value is AuthTelegramRequest {
    if (!('initdata' in value) || value['initdata'] === undefined) return false;
    return true;
}

export function AuthTelegramRequestFromJSON(json: any): AuthTelegramRequest {
    return AuthTelegramRequestFromJSONTyped(json, false);
}

export function AuthTelegramRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTelegramRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'initdata': json['initdata'],
    };
}

export function AuthTelegramRequestToJSON(json: any): AuthTelegramRequest {
    return AuthTelegramRequestToJSONTyped(json, false);
}

export function AuthTelegramRequestToJSONTyped(value?: AuthTelegramRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'initdata': value['initdata'],
    };
}

