/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserDepositsResponse,
} from '../models/index';
import {
    UserDepositsResponseFromJSON,
    UserDepositsResponseToJSON,
} from '../models/index';

export interface GetUserDepositsRequest {
    user?: string;
    reserve?: string;
    cursor?: number;
    limit?: number;
}

/**
 * 
 */
export class DepositsApi extends runtime.BaseAPI {

    /**
     * Get user deposits of Lendingpool
     * Get user deposits of Lendingpool
     */
    async getUserDepositsRaw(requestParameters: GetUserDepositsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDepositsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['user'] != null) {
            queryParameters['user'] = requestParameters['user'];
        }

        if (requestParameters['reserve'] != null) {
            queryParameters['reserve'] = requestParameters['reserve'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2/lendingpool/deposits`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDepositsResponseFromJSON(jsonValue));
    }

    /**
     * Get user deposits of Lendingpool
     * Get user deposits of Lendingpool
     */
    async getUserDeposits(requestParameters: GetUserDepositsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDepositsResponse> {
        const response = await this.getUserDepositsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
