/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QuoteRequest,
  QuoteResponse,
} from '../models/index';
import {
    QuoteRequestFromJSON,
    QuoteRequestToJSON,
    QuoteResponseFromJSON,
    QuoteResponseToJSON,
} from '../models/index';

export interface GetSwapQuoteRequest {
    quoteRequest: QuoteRequest;
}

/**
 * 
 */
export class SwapApi extends runtime.BaseAPI {

    /**
     * Get a quote for a swap
     * Get a quote for a swap
     */
    async getSwapQuoteRaw(requestParameters: GetSwapQuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuoteResponse>> {
        if (requestParameters['quoteRequest'] == null) {
            throw new runtime.RequiredError(
                'quoteRequest',
                'Required parameter "quoteRequest" was null or undefined when calling getSwapQuote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v2/swap/quote`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuoteRequestToJSON(requestParameters['quoteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuoteResponseFromJSON(jsonValue));
    }

    /**
     * Get a quote for a swap
     * Get a quote for a swap
     */
    async getSwapQuote(requestParameters: GetSwapQuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuoteResponse> {
        const response = await this.getSwapQuoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
