/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class WebsocketApi extends runtime.BaseAPI {

    /**
     * Upgrade to websocket connection
     * Websocket Upgrade
     */
    async getUnfilledOrdersWebsocketRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2/ws`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upgrade to websocket connection
     * Websocket Upgrade
     */
    async getUnfilledOrdersWebsocket(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getUnfilledOrdersWebsocketRaw(initOverrides);
    }

}
