/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EIP712SignRequest } from './EIP712SignRequest';
import {
    instanceOfEIP712SignRequest,
    EIP712SignRequestFromJSON,
    EIP712SignRequestFromJSONTyped,
    EIP712SignRequestToJSON,
} from './EIP712SignRequest';
import type { PersonalSignRequest } from './PersonalSignRequest';
import {
    instanceOfPersonalSignRequest,
    PersonalSignRequestFromJSON,
    PersonalSignRequestFromJSONTyped,
    PersonalSignRequestToJSON,
} from './PersonalSignRequest';
import type { PreparedTx } from './PreparedTx';
import {
    instanceOfPreparedTx,
    PreparedTxFromJSON,
    PreparedTxFromJSONTyped,
    PreparedTxToJSON,
} from './PreparedTx';

/**
 * @type ChainActivityStepData
 * 
 * @export
 */
export type ChainActivityStepData = EIP712SignRequest | PersonalSignRequest | PreparedTx;

export function ChainActivityStepDataFromJSON(json: any): ChainActivityStepData {
    return ChainActivityStepDataFromJSONTyped(json, false);
}

export function ChainActivityStepDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainActivityStepData {
    if (json == null) {
        return json;
    }
    if (instanceOfEIP712SignRequest(json)) {
        return EIP712SignRequestFromJSONTyped(json, true);
    }
    if (instanceOfPersonalSignRequest(json)) {
        return PersonalSignRequestFromJSONTyped(json, true);
    }
    if (instanceOfPreparedTx(json)) {
        return PreparedTxFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ChainActivityStepDataToJSON(json: any): any {
    return ChainActivityStepDataToJSONTyped(json, false);
}

export function ChainActivityStepDataToJSONTyped(value?: ChainActivityStepData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfEIP712SignRequest(value)) {
        return EIP712SignRequestToJSON(value as EIP712SignRequest);
    }
    if (instanceOfPersonalSignRequest(value)) {
        return PersonalSignRequestToJSON(value as PersonalSignRequest);
    }
    if (instanceOfPreparedTx(value)) {
        return PreparedTxToJSON(value as PreparedTx);
    }

    return {};
}

