/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventDomain } from './EventDomain';
import {
    EventDomainFromJSON,
    EventDomainFromJSONTyped,
    EventDomainToJSON,
    EventDomainToJSONTyped,
} from './EventDomain';
import type { EventType } from './EventType';
import {
    EventTypeFromJSON,
    EventTypeFromJSONTyped,
    EventTypeToJSON,
    EventTypeToJSONTyped,
} from './EventType';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
    LogToJSONTyped,
} from './Log';
import type { EventName } from './EventName';
import {
    EventNameFromJSON,
    EventNameFromJSONTyped,
    EventNameToJSON,
    EventNameToJSONTyped,
} from './EventName';

/**
 * 
 * @export
 * @interface ExtendedEvent
 */
export interface ExtendedEvent {
    /**
     * 
     * @type {EventDomain}
     * @memberof ExtendedEvent
     */
    domain: EventDomain;
    /**
     * Identifier for the event.
     * @type {number}
     * @memberof ExtendedEvent
     */
    id: number;
    /**
     * 
     * @type {EventName}
     * @memberof ExtendedEvent
     */
    name: EventName;
    /**
     * 
     * @type {Log}
     * @memberof ExtendedEvent
     */
    raw: Log;
    /**
     * 
     * @type {EventType}
     * @memberof ExtendedEvent
     */
    type: EventType;
    /**
     * The payload of the event. The payload is a JSON-marshalled
     * @type {{ [key: string]: any; }}
     * @memberof ExtendedEvent
     */
    payload: { [key: string]: any; };
}



/**
 * Check if a given object implements the ExtendedEvent interface.
 */
export function instanceOfExtendedEvent(value: object): value is ExtendedEvent {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('raw' in value) || value['raw'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function ExtendedEventFromJSON(json: any): ExtendedEvent {
    return ExtendedEventFromJSONTyped(json, false);
}

export function ExtendedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': EventDomainFromJSON(json['domain']),
        'id': json['id'],
        'name': EventNameFromJSON(json['name']),
        'raw': LogFromJSON(json['raw']),
        'type': EventTypeFromJSON(json['type']),
        'payload': json['payload'],
    };
}

export function ExtendedEventToJSON(json: any): ExtendedEvent {
    return ExtendedEventToJSONTyped(json, false);
}

export function ExtendedEventToJSONTyped(value?: ExtendedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': EventDomainToJSON(value['domain']),
        'id': value['id'],
        'name': EventNameToJSON(value['name']),
        'raw': LogToJSON(value['raw']),
        'type': EventTypeToJSON(value['type']),
        'payload': value['payload'],
    };
}

