/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LendingpoolUseAssetAsCollateralTxRequest
 */
export interface LendingpoolUseAssetAsCollateralTxRequest {
    /**
     * Ethereum address of the user
     * @type {string}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    user: string;
    /**
     * Symbol of asset
     * @type {string}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    symbol: string;
    /**
     * Enable or disable the asset as collateral
     * @type {boolean}
     * @memberof LendingpoolUseAssetAsCollateralTxRequest
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the LendingpoolUseAssetAsCollateralTxRequest interface.
 */
export function instanceOfLendingpoolUseAssetAsCollateralTxRequest(value: object): value is LendingpoolUseAssetAsCollateralTxRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function LendingpoolUseAssetAsCollateralTxRequestFromJSON(json: any): LendingpoolUseAssetAsCollateralTxRequest {
    return LendingpoolUseAssetAsCollateralTxRequestFromJSONTyped(json, false);
}

export function LendingpoolUseAssetAsCollateralTxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LendingpoolUseAssetAsCollateralTxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'symbol': json['symbol'],
        'enabled': json['enabled'],
    };
}

export function LendingpoolUseAssetAsCollateralTxRequestToJSON(json: any): LendingpoolUseAssetAsCollateralTxRequest {
    return LendingpoolUseAssetAsCollateralTxRequestToJSONTyped(json, false);
}

export function LendingpoolUseAssetAsCollateralTxRequestToJSONTyped(value?: LendingpoolUseAssetAsCollateralTxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'symbol': value['symbol'],
        'enabled': value['enabled'],
    };
}

