/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeRange
 */
export interface TimeRange {
    /**
     * 
     * @type {Date}
     * @memberof TimeRange
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeRange
     */
    to?: Date;
}

/**
 * Check if a given object implements the TimeRange interface.
 */
export function instanceOfTimeRange(value: object): value is TimeRange {
    return true;
}

export function TimeRangeFromJSON(json: any): TimeRange {
    return TimeRangeFromJSONTyped(json, false);
}

export function TimeRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeRange {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
    };
}

export function TimeRangeToJSON(json: any): TimeRange {
    return TimeRangeToJSONTyped(json, false);
}

export function TimeRangeToJSONTyped(value?: TimeRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
    };
}

