/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BankInfo } from './bank-info';

/**
 * 
 * @export
 * @interface KycResponse
 */
export interface KycResponse {
    /**
     * KYC request ID
     * @type {string}
     * @memberof KycResponse
     */
    'id': string;
    /**
     * First name
     * @type {string}
     * @memberof KycResponse
     */
    'firstName': string;
    /**
     * Last name
     * @type {string}
     * @memberof KycResponse
     */
    'lastName': string;
    /**
     * National code
     * @type {string}
     * @memberof KycResponse
     */
    'nationalId': string;
    /**
     * Date of birth
     * @type {string}
     * @memberof KycResponse
     */
    'dateOfBirth': string;
    /**
     * 
     * @type {BankInfo}
     * @memberof KycResponse
     */
    'bankInfo': BankInfo;
}

