/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The loan to value percentage options
*/
export enum LoanToValueOptions {
    Risky = <any> 'Risky',
    Normal = <any> 'Normal',
    Safe = <any> 'Safe'
}
