/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Coin } from './coin';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { DetailedLoanToValueOptions } from './detailed-loan-to-value-options';

/**
 * 
 * @export
 * @interface LoanPlan
 */
export interface LoanPlan {
    /**
     * The name of the loan plan
     * @type {string}
     * @memberof LoanPlan
     */
    'name': string;
    /**
     * The minimum collateralization ratio of the loan plan
     * @type {string}
     * @memberof LoanPlan
     */
    'minCollateralizationRatio': string;
    /**
     * 
     * @type {Array<Coin>}
     * @memberof LoanPlan
     */
    'acceptableCoins': Array<Coin>;
    /**
     * The annual fee of the loan plan
     * @type {string}
     * @memberof LoanPlan
     */
    'fee': string;
    /**
     * 
     * @type {Currency}
     * @memberof LoanPlan
     */
    'maxDebt': Currency;
    /**
     * 
     * @type {Currency}
     * @memberof LoanPlan
     */
    'minDebt': Currency;
    /**
     * 
     * @type {Array<DetailedLoanToValueOptions>}
     * @memberof LoanPlan
     */
    'loanToValueOptions': Array<DetailedLoanToValueOptions>;
}

