/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Timestamp } from './timestamp';

export class Task {
    /**
    * Task ID
    */
    'id': string;
    /**
    * Task description
    */
    'description': string;
    /**
    * Task reward
    */
    'points': number;
    /**
    * Task status. Possible values \"Pending\", \"Completed\"
    */
    'status': string;
    'completedAt'?: Timestamp;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Timestamp"
        }    ];

    static getAttributeTypeMap() {
        return Task.attributeTypeMap;
    }
}

