/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Currency } from './currency';
import { ExternalTransaction } from './externalTransaction';
import { Symbol } from './symbol';
import { Timestamp } from './timestamp';
import { TransactionType } from './transactionType';

export class Transaction {
    /**
    * Unique identifier of the transaction
    */
    'id': number;
    'time': Timestamp;
    'type': TransactionType;
    /**
    * The ID of the user from whom the transaction originated
    */
    'from': string;
    /**
    * The ID of the user to whom the transaction is directed
    */
    'to': string;
    'symbol': Symbol;
    'amount': Currency;
    /**
    * Equal to \"Inbound\" if the transaction is directed to the user, and \"Outbound\" if the transaction is directed from the user.
    */
    'direction': Transaction.DirectionEnum;
    'externalTransaction'?: ExternalTransaction;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "Timestamp"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TransactionType"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "Symbol"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Currency"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "Transaction.DirectionEnum"
        },
        {
            "name": "externalTransaction",
            "baseName": "externalTransaction",
            "type": "ExternalTransaction"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}

export namespace Transaction {
    export enum DirectionEnum {
        Inbound = <any> 'Inbound',
        Outbound = <any> 'Outbound'
    }
}
