/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TransactionStatus = {
    SENT: 'Sent',
    SUCCESS: 'Success',
    FAILED: 'Failed'
} as const;

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];



