/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Ilk } from '../model';
// @ts-ignore
import type { IlksResponse } from '../model';
/**
 * IlksApi - axios parameter creator
 * @export
 */
export const IlksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve a list of all available ilks.
         * @summary Get all Ilks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIlks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/ilks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve an Ilk by providing its name.
         * @summary Get Ilk by name
         * @param {string} name Name of the ILK
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIlkByName: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getIlkByName', 'name', name)
            const localVarPath = `/v2/ilks/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IlksApi - functional programming interface
 * @export
 */
export const IlksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IlksApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve a list of all available ilks.
         * @summary Get all Ilks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllIlks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IlksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllIlks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IlksApi.getAllIlks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve an Ilk by providing its name.
         * @summary Get Ilk by name
         * @param {string} name Name of the ILK
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIlkByName(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Ilk>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIlkByName(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IlksApi.getIlkByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IlksApi - factory interface
 * @export
 */
export const IlksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IlksApiFp(configuration)
    return {
        /**
         * Retrieve a list of all available ilks.
         * @summary Get all Ilks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIlks(options?: RawAxiosRequestConfig): AxiosPromise<IlksResponse> {
            return localVarFp.getAllIlks(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve an Ilk by providing its name.
         * @summary Get Ilk by name
         * @param {string} name Name of the ILK
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIlkByName(name: string, options?: RawAxiosRequestConfig): AxiosPromise<Ilk> {
            return localVarFp.getIlkByName(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IlksApi - interface
 * @export
 * @interface IlksApi
 */
export interface IlksApiInterface {
    /**
     * Retrieve a list of all available ilks.
     * @summary Get all Ilks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IlksApiInterface
     */
    getAllIlks(options?: RawAxiosRequestConfig): AxiosPromise<IlksResponse>;

    /**
     * Retrieve an Ilk by providing its name.
     * @summary Get Ilk by name
     * @param {string} name Name of the ILK
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IlksApiInterface
     */
    getIlkByName(name: string, options?: RawAxiosRequestConfig): AxiosPromise<Ilk>;

}

/**
 * IlksApi - object-oriented interface
 * @export
 * @class IlksApi
 * @extends {BaseAPI}
 */
export class IlksApi extends BaseAPI implements IlksApiInterface {
    /**
     * Retrieve a list of all available ilks.
     * @summary Get all Ilks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IlksApi
     */
    public getAllIlks(options?: RawAxiosRequestConfig) {
        return IlksApiFp(this.configuration).getAllIlks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve an Ilk by providing its name.
     * @summary Get Ilk by name
     * @param {string} name Name of the ILK
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IlksApi
     */
    public getIlkByName(name: string, options?: RawAxiosRequestConfig) {
        return IlksApiFp(this.configuration).getIlkByName(name, options).then((request) => request(this.axios, this.basePath));
    }
}

