/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuthTelegramRequest } from '../model';
// @ts-ignore
import type { JwtResponse } from '../model';
// @ts-ignore
import type { LoginRequest } from '../model';
// @ts-ignore
import type { SignUpRequest } from '../model';
// @ts-ignore
import type { SimpleResponse } from '../model';
// @ts-ignore
import type { UserError } from '../model';
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Authenticate with Telegram and get a JWT token.
         * @summary Authenticate with Telegram
         * @param {AuthTelegramRequest} authTelegramRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateWithTelegram: async (authTelegramRequest: AuthTelegramRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authTelegramRequest' is not null or undefined
            assertParamExists('authenticateWithTelegram', 'authTelegramRequest', authTelegramRequest)
            const localVarPath = `/auth/telegram`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authTelegramRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generate a JWT token.
         * @summary Generate a JWT token
         * @param {GenerateJwtTokenDurationEnum} duration Token duration in days
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateJwtToken: async (duration: GenerateJwtTokenDurationEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'duration' is not null or undefined
            assertParamExists('generateJwtToken', 'duration', duration)
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (duration !== undefined) {
                localVarQueryParameter['duration'] = duration;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get OTP for the user.
         * @summary Get OTP
         * @param {GetOtpChannelEnum} channel Channel to send OTP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOtp: async (channel: GetOtpChannelEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('getOtp', 'channel', channel)
            const localVarPath = `/auth/otp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (channel !== undefined) {
                localVarQueryParameter['channel'] = channel;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Login with email and password and get a JWT token.
         * @summary Login with email and password
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginWithEmailAndPassword: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('loginWithEmailAndPassword', 'loginRequest', loginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * signup with email and password and get a JWT token.
         * @summary signup with email and password
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupWithEmailAndPassword: async (signUpRequest: SignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpRequest' is not null or undefined
            assertParamExists('signupWithEmailAndPassword', 'signUpRequest', signUpRequest)
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verify the email of the user.
         * @summary Verify email
         * @param {string} token Verification token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyUserEmail: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('verifyUserEmail', 'token', token)
            const localVarPath = `/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Authenticate with Telegram and get a JWT token.
         * @summary Authenticate with Telegram
         * @param {AuthTelegramRequest} authTelegramRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticateWithTelegram(authTelegramRequest: AuthTelegramRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JwtResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticateWithTelegram(authTelegramRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authenticateWithTelegram']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generate a JWT token.
         * @summary Generate a JWT token
         * @param {GenerateJwtTokenDurationEnum} duration Token duration in days
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateJwtToken(duration: GenerateJwtTokenDurationEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JwtResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateJwtToken(duration, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.generateJwtToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get OTP for the user.
         * @summary Get OTP
         * @param {GetOtpChannelEnum} channel Channel to send OTP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOtp(channel: GetOtpChannelEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SimpleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOtp(channel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.getOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Login with email and password and get a JWT token.
         * @summary Login with email and password
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginWithEmailAndPassword(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JwtResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginWithEmailAndPassword(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginWithEmailAndPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * signup with email and password and get a JWT token.
         * @summary signup with email and password
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signupWithEmailAndPassword(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SimpleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signupWithEmailAndPassword(signUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signupWithEmailAndPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Verify the email of the user.
         * @summary Verify email
         * @param {string} token Verification token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyUserEmail(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JwtResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyUserEmail(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.verifyUserEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Authenticate with Telegram and get a JWT token.
         * @summary Authenticate with Telegram
         * @param {AuthTelegramRequest} authTelegramRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateWithTelegram(authTelegramRequest: AuthTelegramRequest, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse> {
            return localVarFp.authenticateWithTelegram(authTelegramRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Generate a JWT token.
         * @summary Generate a JWT token
         * @param {GenerateJwtTokenDurationEnum} duration Token duration in days
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateJwtToken(duration: GenerateJwtTokenDurationEnum, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse> {
            return localVarFp.generateJwtToken(duration, options).then((request) => request(axios, basePath));
        },
        /**
         * Get OTP for the user.
         * @summary Get OTP
         * @param {GetOtpChannelEnum} channel Channel to send OTP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOtp(channel: GetOtpChannelEnum, options?: RawAxiosRequestConfig): AxiosPromise<SimpleResponse> {
            return localVarFp.getOtp(channel, options).then((request) => request(axios, basePath));
        },
        /**
         * Login with email and password and get a JWT token.
         * @summary Login with email and password
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginWithEmailAndPassword(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse> {
            return localVarFp.loginWithEmailAndPassword(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * signup with email and password and get a JWT token.
         * @summary signup with email and password
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupWithEmailAndPassword(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<SimpleResponse> {
            return localVarFp.signupWithEmailAndPassword(signUpRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verify the email of the user.
         * @summary Verify email
         * @param {string} token Verification token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyUserEmail(token: string, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse> {
            return localVarFp.verifyUserEmail(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 * @export
 * @interface AuthApi
 */
export interface AuthApiInterface {
    /**
     * Authenticate with Telegram and get a JWT token.
     * @summary Authenticate with Telegram
     * @param {AuthTelegramRequest} authTelegramRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authenticateWithTelegram(authTelegramRequest: AuthTelegramRequest, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse>;

    /**
     * Generate a JWT token.
     * @summary Generate a JWT token
     * @param {GenerateJwtTokenDurationEnum} duration Token duration in days
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    generateJwtToken(duration: GenerateJwtTokenDurationEnum, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse>;

    /**
     * Get OTP for the user.
     * @summary Get OTP
     * @param {GetOtpChannelEnum} channel Channel to send OTP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    getOtp(channel: GetOtpChannelEnum, options?: RawAxiosRequestConfig): AxiosPromise<SimpleResponse>;

    /**
     * Login with email and password and get a JWT token.
     * @summary Login with email and password
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    loginWithEmailAndPassword(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse>;

    /**
     * signup with email and password and get a JWT token.
     * @summary signup with email and password
     * @param {SignUpRequest} signUpRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    signupWithEmailAndPassword(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<SimpleResponse>;

    /**
     * Verify the email of the user.
     * @summary Verify email
     * @param {string} token Verification token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    verifyUserEmail(token: string, options?: RawAxiosRequestConfig): AxiosPromise<JwtResponse>;

}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * Authenticate with Telegram and get a JWT token.
     * @summary Authenticate with Telegram
     * @param {AuthTelegramRequest} authTelegramRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authenticateWithTelegram(authTelegramRequest: AuthTelegramRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authenticateWithTelegram(authTelegramRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generate a JWT token.
     * @summary Generate a JWT token
     * @param {GenerateJwtTokenDurationEnum} duration Token duration in days
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public generateJwtToken(duration: GenerateJwtTokenDurationEnum, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).generateJwtToken(duration, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get OTP for the user.
     * @summary Get OTP
     * @param {GetOtpChannelEnum} channel Channel to send OTP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public getOtp(channel: GetOtpChannelEnum, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).getOtp(channel, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Login with email and password and get a JWT token.
     * @summary Login with email and password
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginWithEmailAndPassword(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginWithEmailAndPassword(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * signup with email and password and get a JWT token.
     * @summary signup with email and password
     * @param {SignUpRequest} signUpRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signupWithEmailAndPassword(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signupWithEmailAndPassword(signUpRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verify the email of the user.
     * @summary Verify email
     * @param {string} token Verification token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public verifyUserEmail(token: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).verifyUserEmail(token, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GenerateJwtTokenDurationEnum = {
    NUMBER_7: 7,
    NUMBER_15: 15,
    NUMBER_30: 30,
    NUMBER_90: 90
} as const;
export type GenerateJwtTokenDurationEnum = typeof GenerateJwtTokenDurationEnum[keyof typeof GenerateJwtTokenDurationEnum];
/**
 * @export
 */
export const GetOtpChannelEnum = {
    PHONE: 'phone'
} as const;
export type GetOtpChannelEnum = typeof GetOtpChannelEnum[keyof typeof GetOtpChannelEnum];
