/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChainActivityStep } from './ChainActivityStep';
import {
    ChainActivityStepFromJSON,
    ChainActivityStepFromJSONTyped,
    ChainActivityStepToJSON,
    ChainActivityStepToJSONTyped,
} from './ChainActivityStep';

/**
 * 
 * @export
 * @interface ChainActivity
 */
export interface ChainActivity {
    /**
     * 
     * @type {number}
     * @memberof ChainActivity
     */
    stepNumber: number;
    /**
     * 
     * @type {number}
     * @memberof ChainActivity
     */
    numberOfSteps: number;
    /**
     * 
     * @type {Array<ChainActivityStep>}
     * @memberof ChainActivity
     */
    steps: Array<ChainActivityStep>;
}

/**
 * Check if a given object implements the ChainActivity interface.
 */
export function instanceOfChainActivity(value: object): value is ChainActivity {
    if (!('stepNumber' in value) || value['stepNumber'] === undefined) return false;
    if (!('numberOfSteps' in value) || value['numberOfSteps'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function ChainActivityFromJSON(json: any): ChainActivity {
    return ChainActivityFromJSONTyped(json, false);
}

export function ChainActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'stepNumber': json['stepNumber'],
        'numberOfSteps': json['numberOfSteps'],
        'steps': ((json['steps'] as Array<any>).map(ChainActivityStepFromJSON)),
    };
}

export function ChainActivityToJSON(json: any): ChainActivity {
    return ChainActivityToJSONTyped(json, false);
}

export function ChainActivityToJSONTyped(value?: ChainActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stepNumber': value['stepNumber'],
        'numberOfSteps': value['numberOfSteps'],
        'steps': ((value['steps'] as Array<any>).map(ChainActivityStepToJSON)),
    };
}

