/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LendingpoolBorrowTxRequest
 */
export interface LendingpoolBorrowTxRequest {
    /**
     * Ethereum address of the user
     * @type {string}
     * @memberof LendingpoolBorrowTxRequest
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof LendingpoolBorrowTxRequest
     */
    symbol: string;
    /**
     * The amount to borrow in native token units
     * @type {string}
     * @memberof LendingpoolBorrowTxRequest
     */
    amount?: string;
}

/**
 * Check if a given object implements the LendingpoolBorrowTxRequest interface.
 */
export function instanceOfLendingpoolBorrowTxRequest(value: object): value is LendingpoolBorrowTxRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function LendingpoolBorrowTxRequestFromJSON(json: any): LendingpoolBorrowTxRequest {
    return LendingpoolBorrowTxRequestFromJSONTyped(json, false);
}

export function LendingpoolBorrowTxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LendingpoolBorrowTxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'symbol': json['symbol'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function LendingpoolBorrowTxRequestToJSON(json: any): LendingpoolBorrowTxRequest {
    return LendingpoolBorrowTxRequestToJSONTyped(json, false);
}

export function LendingpoolBorrowTxRequestToJSONTyped(value?: LendingpoolBorrowTxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'symbol': value['symbol'],
        'amount': value['amount'],
    };
}

