/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MethodParameters
 */
export interface MethodParameters {
    /**
     * 
     * @type {string}
     * @memberof MethodParameters
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof MethodParameters
     */
    calldata: string;
    /**
     * 
     * @type {string}
     * @memberof MethodParameters
     */
    value: string;
}

/**
 * Check if a given object implements the MethodParameters interface.
 */
export function instanceOfMethodParameters(value: object): value is MethodParameters {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('calldata' in value) || value['calldata'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MethodParametersFromJSON(json: any): MethodParameters {
    return MethodParametersFromJSONTyped(json, false);
}

export function MethodParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'calldata': json['calldata'],
        'value': json['value'],
    };
}

export function MethodParametersToJSON(json: any): MethodParameters {
    return MethodParametersToJSONTyped(json, false);
}

export function MethodParametersToJSONTyped(value?: MethodParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'calldata': value['calldata'],
        'value': value['value'],
    };
}

