/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StablecoinSystemMintZarTxRequest
 */
export interface StablecoinSystemMintZarTxRequest {
    /**
     * Ethereum address of the user
     * @type {string}
     * @memberof StablecoinSystemMintZarTxRequest
     */
    user: string;
    /**
     * The ID of the vault
     * @type {number}
     * @memberof StablecoinSystemMintZarTxRequest
     */
    vaultId: number;
    /**
     * The amount of stablecoin to mint in native token units, if not provided, it will be calculated based on the available to mint amount
     * @type {string}
     * @memberof StablecoinSystemMintZarTxRequest
     */
    amount?: string;
}

/**
 * Check if a given object implements the StablecoinSystemMintZarTxRequest interface.
 */
export function instanceOfStablecoinSystemMintZarTxRequest(value: object): value is StablecoinSystemMintZarTxRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    return true;
}

export function StablecoinSystemMintZarTxRequestFromJSON(json: any): StablecoinSystemMintZarTxRequest {
    return StablecoinSystemMintZarTxRequestFromJSONTyped(json, false);
}

export function StablecoinSystemMintZarTxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StablecoinSystemMintZarTxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'vaultId': json['vaultId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function StablecoinSystemMintZarTxRequestToJSON(json: any): StablecoinSystemMintZarTxRequest {
    return StablecoinSystemMintZarTxRequestToJSONTyped(json, false);
}

export function StablecoinSystemMintZarTxRequestToJSONTyped(value?: StablecoinSystemMintZarTxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'vaultId': value['vaultId'],
        'amount': value['amount'],
    };
}

