/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StablecoinSystemDepositCollateralTxRequest
 */
export interface StablecoinSystemDepositCollateralTxRequest {
    /**
     * Ethereum address of the user
     * @type {string}
     * @memberof StablecoinSystemDepositCollateralTxRequest
     */
    user: string;
    /**
     * The ID of the vault
     * @type {number}
     * @memberof StablecoinSystemDepositCollateralTxRequest
     */
    vaultId: number;
    /**
     * The amount of collateral to deposit in native token units, if not provided, it will be calculated based on the wallet balance
     * @type {string}
     * @memberof StablecoinSystemDepositCollateralTxRequest
     */
    amount?: string;
}

/**
 * Check if a given object implements the StablecoinSystemDepositCollateralTxRequest interface.
 */
export function instanceOfStablecoinSystemDepositCollateralTxRequest(value: object): value is StablecoinSystemDepositCollateralTxRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    return true;
}

export function StablecoinSystemDepositCollateralTxRequestFromJSON(json: any): StablecoinSystemDepositCollateralTxRequest {
    return StablecoinSystemDepositCollateralTxRequestFromJSONTyped(json, false);
}

export function StablecoinSystemDepositCollateralTxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StablecoinSystemDepositCollateralTxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'vaultId': json['vaultId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function StablecoinSystemDepositCollateralTxRequestToJSON(json: any): StablecoinSystemDepositCollateralTxRequest {
    return StablecoinSystemDepositCollateralTxRequestToJSONTyped(json, false);
}

export function StablecoinSystemDepositCollateralTxRequestToJSONTyped(value?: StablecoinSystemDepositCollateralTxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'vaultId': value['vaultId'],
        'amount': value['amount'],
    };
}

