/* tslint:disable */
/* eslint-disable */
/**
 * Zarban API
 * API for Zarban services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * System surplus buffer
 * @export
 * @interface SystemSurplusBuffer
 */
export interface SystemSurplusBuffer {
}

/**
 * Check if a given object implements the SystemSurplusBuffer interface.
 */
export function instanceOfSystemSurplusBuffer(value: object): value is SystemSurplusBuffer {
    return true;
}

export function SystemSurplusBufferFromJSON(json: any): SystemSurplusBuffer {
    return SystemSurplusBufferFromJSONTyped(json, false);
}

export function SystemSurplusBufferFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemSurplusBuffer {
    return json;
}

export function SystemSurplusBufferToJSON(json: any): SystemSurplusBuffer {
    return SystemSurplusBufferToJSONTyped(json, false);
}

export function SystemSurplusBufferToJSONTyped(value?: SystemSurplusBuffer | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

