/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransactionResponse,
} from '../models/index';
import {
    TransactionResponseFromJSON,
    TransactionResponseToJSON,
} from '../models/index';

export interface GetUserTransactionsRequest {
    cursor?: number;
    limit?: number;
}

/**
 * TransactionsApi - interface
 * 
 * @export
 * @interface TransactionsApiInterface
 */
export interface TransactionsApiInterface {
    /**
     * Get a list of the recent transactions of the user.
     * @summary Get user transactions
     * @param {number} [cursor] Cursor for pagination
     * @param {number} [limit] Limit the number of transactions returned (default is 100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    getUserTransactionsRaw(requestParameters: GetUserTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionResponse>>;

    /**
     * Get a list of the recent transactions of the user.
     * Get user transactions
     */
    getUserTransactions(requestParameters: GetUserTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionResponse>;

}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI implements TransactionsApiInterface {

    /**
     * Get a list of the recent transactions of the user.
     * Get user transactions
     */
    async getUserTransactionsRaw(requestParameters: GetUserTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of the recent transactions of the user.
     * Get user transactions
     */
    async getUserTransactions(requestParameters: GetUserTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionResponse> {
        const response = await this.getUserTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
