/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailOtpSubmitRequest
 */
export interface EmailOtpSubmitRequest {
    /**
     * OTP code
     * @type {number}
     * @memberof EmailOtpSubmitRequest
     */
    code: number;
}

/**
 * Check if a given object implements the EmailOtpSubmitRequest interface.
 */
export function instanceOfEmailOtpSubmitRequest(value: object): value is EmailOtpSubmitRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function EmailOtpSubmitRequestFromJSON(json: any): EmailOtpSubmitRequest {
    return EmailOtpSubmitRequestFromJSONTyped(json, false);
}

export function EmailOtpSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailOtpSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function EmailOtpSubmitRequestToJSON(json: any): EmailOtpSubmitRequest {
    return EmailOtpSubmitRequestToJSONTyped(json, false);
}

export function EmailOtpSubmitRequestToJSONTyped(value?: EmailOtpSubmitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

