/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Redemption } from './Redemption';
import {
    RedemptionFromJSON,
    RedemptionFromJSONTyped,
    RedemptionToJSON,
    RedemptionToJSONTyped,
} from './Redemption';

/**
 * 
 * @export
 * @interface RedemptionResponse
 */
export interface RedemptionResponse {
    /**
     * 
     * @type {Array<Redemption>}
     * @memberof RedemptionResponse
     */
    data: Array<Redemption>;
}

/**
 * Check if a given object implements the RedemptionResponse interface.
 */
export function instanceOfRedemptionResponse(value: object): value is RedemptionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RedemptionResponseFromJSON(json: any): RedemptionResponse {
    return RedemptionResponseFromJSONTyped(json, false);
}

export function RedemptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedemptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RedemptionFromJSON)),
    };
}

export function RedemptionResponseToJSON(json: any): RedemptionResponse {
    return RedemptionResponseToJSONTyped(json, false);
}

export function RedemptionResponseToJSONTyped(value?: RedemptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(RedemptionToJSON)),
    };
}

