/* tslint:disable */
/* eslint-disable */
/**
 * Zarban Wallet API
 * API for Zarban wallet services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@zarban.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleResponse
 */
export interface SimpleResponse {
    /**
     * Localized messages
     * @type {{ [key: string]: string; }}
     * @memberof SimpleResponse
     */
    messages: { [key: string]: string; };
}

/**
 * Check if a given object implements the SimpleResponse interface.
 */
export function instanceOfSimpleResponse(value: object): value is SimpleResponse {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function SimpleResponseFromJSON(json: any): SimpleResponse {
    return SimpleResponseFromJSONTyped(json, false);
}

export function SimpleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'],
    };
}

export function SimpleResponseToJSON(json: any): SimpleResponse {
    return SimpleResponseToJSONTyped(json, false);
}

export function SimpleResponseToJSONTyped(value?: SimpleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'],
    };
}

